import "../styles/globals.css";
import { Inter } from "next/font/google";
import Nav from "../components/nav";
import "../components/nav.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LaunchDarkly Demo",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
